Definitions: {
    ...@generated/image_content
    ...@generated/image
    ...@generated/image_info
    ...@generated/image_type
    ...@generated/image_parameter
    ...@generated/image_vector

    ...@parts/def-gen-structures
    ...@parts/tcl-obj
}

Geometry: {
    ...@generated/geometry

    style.fill: lightyellow
}

Definitions.image."F content"		-> Definitions.image_content	: "content (n:1)"
Definitions.image."F meta" 		-> Definitions.Tcl_Obj		: "meta (n:1)"

Definitions.image_content."F opspec"	-> Definitions.image_type	: "opspec"
Definitions.image_content."F public"	-> Definitions.image_info	: "public\nINLINED"

Definitions.image_type."F param"	-> Definitions.image_parameter	: "param"

Definitions.image_info."F domain"	-> Geometry.geometry		: "domain\nINLINED"
Definitions.image_info."F srcs"		-> Definitions.image_vector    	: "srcs\nINLINED"
Definitions.image_info."F param"	-> Definitions."<op>param"		: param
Definitions.image_info."F state"	-> Definitions."<op>state -fields"	: state

## backward arrow is a problem, jumbles the layout
## Definitions.image_vector."F v"		-> Definitions.image

## //////////////////////////////////

"definition pipeline" -> Definitions.image
"definition pipeline".style.fill: lightgreen
"definition pipeline".shape: oval
