...@generated/cc_block
...@generated/cc
...@generated/cc_row
...@generated/cc_range

direction: up
cc_range."F owner"	-> cc		: "owner"

direction: left
cc."F owner"		-> cc_block	: "owner"

direction: down
cc_block."F row_first"	-> cc_row	: "row_first"
cc."F first"		-> cc_range	: "first"

direction: right
cc_block."F cc_first"	-> cc		: "cc_first"
cc_row."F first"	-> cc_range	: "first"
