Runtime: {
    ...@generated/block
    ...@generated/context
    ...@generated/region
    ...@generated/region_info
    ...@generated/region_vector

    ...@parts/runtime-gen-structures
}

Geometry: {
    ...@generated/geometry
    ...@generated/point

    style.fill: lightyellow
}

Definitions: {
    ...@generated/image
    ...@generated/image_type

    ...@parts/def-gen-structures

    style.fill: lightyellow
}

Runtime.region."F opspec"	-> Definitions.image_type	: "opspec"
Runtime.region."F origin"	-> Definitions.image		: "origin"
Runtime.region."F pixels"	-> Runtime.block		: "pixels\nINLINED"
Runtime.region."F public"	-> Runtime.region_info		: "public\nINLINED"
Runtime.region."F c"		-> Runtime.context		: "c (n:1)"

Runtime.region_info."F srcs"	-> Runtime.region_vector	: "srcs\nINLINED"
Runtime.region_info."F domain"	-> Geometry.geometry		: "domain"
Runtime.region_info."F state"	-> Runtime."<op>pixel -fields"		: state
Runtime.region_info."F istate"	-> Definitions."<op>state -fields"	: istate
Runtime.region_info."F param"	-> Definitions."<op>param"		: param

Runtime.block."F region"	-> Runtime.region		: "region"
Runtime.block."F location"	-> Geometry.point		: "location\nINLINED"
Runtime.block."F domain"	-> Geometry.geometry		: "domain\nINLINED"

## backward arrow jumbles layout
## Runtime.region_vector."F v"	-> Runtime.region

## //////////////////////////////////

"execution pipeline" -> Runtime.region
"execution pipeline".style.fill: lightgreen
"execution pipeline".shape: oval
