#!/bin/bash
SUDO="$(sudoit)"
PREFIX="bench"
#TRACE="-trace"

${SUDO} ./build.tcl uninstall
clear
echo

mkdir -p "${LOG}"
rm    -f "${LOG}/${PREFIX}".*

# Cleanups
rm -vf *.trace */*.trace
find . -follow -name "core*" -exec rm "{}" \;
pca

# include dir is sibling of bin dir
headers="$(dirname $(dirname $(type tclsh | projection 3))/include)"

( time ${SUDO} ./build.tcl $TRACE bench \
       --log   "${LOG}"/${PREFIX} \
       --color on \
       "$@"

) 2>&1 | tee "${LOG}"/${PREFIX}.stderr

# post-processing
# I.  convert into a .sqlite database
# II. generate a number of extracts and charts

bench-to-sqlite \
    "${LOG}"/${PREFIX}.sqlite  \
    "${LOG}"/${PREFIX}.results

########################################
exit

bench-charts \
    "${LOG}"/${PREFIX}.sqlite \
    bench/*.charts

gnuplot bench/image-from-value.gnuplot

mv *.csv image-from-value.ps bench/plots

#less -rf "${LOG}"/${PREFIX}.stderr
