#!/bin/bash
# abort on error
set -e

## inlined clean (backup files, crash dumps, debug traces)
find . -name "*~" -print
find . -name "*~" -exec rm "{}" \;
find . -follow -name "core*" -exec rm "{}" \;
rm -f *.trace

operation=install
#operation=debug

# setup of inlined/integrated doc
rm -rf        doc
cp -rf docsrc doc
mkdir -p      doc/ref
cp -r  doc/parts  doc/assets
rm doc/assets/aktive-logo-32.ico
rm doc/assets/aktive-logo-128.ppm
rm doc/assets/aktive-logo-128-pipeline.d2
rm doc/assets/aktive-logo-128-pipeline.png
rm doc/assets/*.inc

# pikchr conversion for docs
for i in doc/assets/*.pikchr
do
    pikchr --svg-only "$i" > "doc/assets/$(basename "$i" .pikchr).svg"
    rm "$i"
done

# main build, including examples, and doc/example integration
mkdir -p ../Logs
( ./build.tcl uninstall $operation "$@" && \
      \
      tclsh examples.tcl && \
      \
      tclsh tools/md-include \
	    -x doc/ref/xref.tcl \
	    -x doc/ref/xmark.tcl \
	    $(find doc -name '*.md' -a -not -name 'example-*')
) |& tee ../Logs/test.install

# doc cleanup
rm -rf doc/parts
rm -rf doc/dev/figures/*.d2
rm -rf doc/dev/figures/generated
rm -rf doc/dev/figures/parts
rm -rf doc/ref/*.tcl
# squash inlined files (<!include: ...>)
rm -rf doc/ref/example-*.md
rm -rf doc/ref/example-*.txt

echo
date
