#!/bin/bash

## inlined clean
find . -name "*~" -print
find . -name "*~" -exec rm "{}" \;
find . -follow -name "core*" -exec rm "{}" \;
rm -f *.trace

mkdir -p ../Logs

$K ./build.tcl bench --log perf "$@" |& tee ../Logs/test.perf

./bench/splat.tcl < perf.results > $$
( head -1 $$ ; tail -n +2 $$ | sort ) > bench/perf.csv
rm $$
rm perf.*
