#!/bin/bash
SUDO="$(sudoit)"
PREFIX="test"

${SUDO} ./build.tcl uninstall
clear
echo

mkdir -p "${LOG}"
rm    -f "${LOG}/${PREFIX}".*

# Cleanups
rm -vf *.trace */*.trace
find . -follow -name "core*" -exec rm "{}" \;
pca

# include dir is sibling of bin dir
headers="$(dirname $(dirname $(type tclsh | projection 3))/include)"

( time ${SUDO} ./build.tcl test \
       --test-include "${headers}" \
       --log   "${LOG}"/${PREFIX} \
       --color on \
       "$@"

  echo
  echo Fixup ...
  for i in $(ls "${LOG}"/${PREFIX}.*|grep -v ${PREFIX}.result)
  do
      echo Fixing $i ...
      ftq < $i > ${i}-f
  done

  echo
  ls "${LOG}"/${PREFIX}.* | grep '\(.-f\)\|\(result\)'

  echo
  date

  test -f "${LOG}"/${PREFIX}.failures && ( cat "${LOG}"/${PREFIX}.failures ; echo )

) 2>&1 | tee "${LOG}"/${PREFIX}.stderr

#less -rf "${LOG}"/${PREFIX}.stderr
